import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics");
  const result = await resp.json();
  return (
    <html lang="en">
      <body>
        <input type="text" placeholder="검색" />
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {/* @ts-ignore */}
          {result.map((e) => {
            return (
              <li key={e.id}>
                <Link href={"/read/" + e.id}>{e.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <button>Delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
